Atividade 3

In [2]:
import numpy as np
import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Download latest version
path = kagglehub.dataset_download("pratyushpuri/ev-electrical-vehicles-dataset-3k-records-2025")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (0.3.13).
Downloading from https://www.kaggle.com/api/v1/datasets/download/pratyushpuri/ev-electrical-vehicles-dataset-3k-records-2025?dataset_version_number=1...

100%|██████████| 508k/508k [00:00<00:00, 79.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/pratyushpuri/ev-electrical-vehicles-dataset-3k-records-2025/versions/1

In [4]:
df = pd.read_csv(path + '/electric_vehicles_dataset.csv')
display(df.head())

,Vehicle_ID,Manufacturer,Model,Year,Battery_Type,Battery_Capacity_kWh,Range_km,Charging_Type,Charge_Time_hr,Price_USD,Color,Country_of_Manufacture,Autonomous_Level,CO2_Emissions_g_per_km,Safety_Rating,Units_Sold_2024,Warranty_Years
0,1,Acura,ZDX (with GM Ultium),2015,Lithium-titanate,55.8,214,CHAdeMO,9.0,111203.94,Matte White,UK,0.0,NaN,5.0,19726,3
1,2,Lamborghini,Revuelto (PHEV),2025,Lithium-titanate,90.8,212,Vehicle-to-Home (V2H),7.3,127131.65,White,Netherlands,2.0,0.0,4.0,3349,3
2,3,NIO,ET7,2020,Calcium-ion,64.7,235,Level 2 Charging,8.9,94347.37,Beige,UK,5.0,0.0,5.0,6300,5
3,4,Audi,e-tron,2025,Lithium-iron phosphate,120.5,140,Ultra-Fast Charging (350 kW+),10.5,75615.15,Sunset Orange,Argentina,2.0,0.0,5.0,2339,5
4,5,Acura,ZDX (with GM Ultium),2023,Lithium-titanate,51.8,336,Plug-in Hydrogen Refueling,3.6,141046.94,Ice Silver,United Arab Emirates,2.0,0.0,3.0,1051,4

In [5]:
df.tail()

,Vehicle_ID,Manufacturer,Model,Year,Battery_Type,Battery_Capacity_kWh,Range_km,Charging_Type,Charge_Time_hr,Price_USD,Color,Country_of_Manufacture,Autonomous_Level,CO2_Emissions_g_per_km,Safety_Rating,Units_Sold_2024,Warranty_Years
3017,3018,Ferrari,SF90 Stradale (PHEV),2018,Sodium-ion,49.9,182,Mobile Charging,11.7,43988.90,Champagne,Indonesia,2.0,0.0,4.0,13366,5
3018,3019,Mahindra,Born Electric (upcoming range),2019,Lithium-ion,136.9,375,Vehicle-to-Home (V2H),5.8,142072.84,Electric Blue,India,NaN,0.0,3.0,15235,3
3019,3020,Cadillac,Lyriq,2021,Lithium-iron phosphate,136.5,221,Plug-in Hydrogen Refueling,1.1,88218.53,Metallic Silver,Canada,2.0,0.0,3.0,13808,3
3020,3021,Mahindra,XUV400,2021,Nickel-metal hydride,96.4,249,Mobile Charging,9.8,110221.30,Matte Green,New Zealand,3.0,NaN,3.0,9854,3
3021,3022,MG,MG4 Electric,2016,Lithium-sulfur,76.2,404,NACS,2.4,148993.26,Matte Black,Austria,5.0,0.0,4.0,5786,5

In [6]:
df.drop([0, 1])

,Vehicle_ID,Manufacturer,Model,Year,Battery_Type,Battery_Capacity_kWh,Range_km,Charging_Type,Charge_Time_hr,Price_USD,Color,Country_of_Manufacture,Autonomous_Level,CO2_Emissions_g_per_km,Safety_Rating,Units_Sold_2024,Warranty_Years
2,3,NIO,ET7,2020,Calcium-ion,64.7,235,Level 2 Charging,8.9,94347.37,Beige,UK,5.0,0.0,5.0,6300,5
3,4,Audi,e-tron,2025,Lithium-iron phosphate,120.5,140,Ultra-Fast Charging (350 kW+),10.5,75615.15,Sunset Orange,Argentina,2.0,0.0,5.0,2339,5
4,5,Acura,ZDX (with GM Ultium),2023,Lithium-titanate,51.8,336,Plug-in Hydrogen Refueling,3.6,141046.94,Ice Silver,United Arab Emirates,2.0,0.0,3.0,1051,4
5,6,XPeng,G9,2016,Lithium-iron phosphate,138.7,390,Mobile Charging,2.9,89907.75,Ruby Red,Australia,NaN,NaN,5.0,8609,5
6,7,Jeep,Recon (upcoming),2024,Nickel-cobalt-aluminum,67.1,170,Vehicle-to-Load (V2L),1.5,35653.97,Orange,Sweden,5.0,0.0,NaN,12504,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3017,3018,Ferrari,SF90 Stradale (PHEV),2018,Sodium-ion,49.9,182,Mobile Charging,11.7,43988.90,Champagne,Indonesia,2.0,0.0,4.0,13366,5
3018,3019,Mahindra,Born Electric (upcoming range),2019,Lithium-ion,136.9,375,Vehicle-to-Home (V2H),5.8,142072.84,Electric Blue,India,NaN,0.0,3.0,15235,3
3019,3020,Cadillac,Lyriq,2021,Lithium-iron phosphate,136.5,221,Plug-in Hydrogen Refueling,1.1,88218.53,Metallic Silver,Canada,2.0,0.0,3.0,13808,3
3020,3021,Mahindra,XUV400,2021,Nickel-metal hydride,96.4,249,Mobile Charging,9.8,110221.30,Matte Green,New Zealand,3.0,NaN,3.0,9854,3
3021,3022,MG,MG4 Electric,2016,Lithium-sulfur,76.2,404,NACS,2.4,148993.26,Matte Black,Austria,5.0,0.0,4.0,5786,5

In [7]:
df.drop('Vehicle_ID', axis=1)

,Manufacturer,Model,Year,Battery_Type,Battery_Capacity_kWh,Range_km,Charging_Type,Charge_Time_hr,Price_USD,Color,Country_of_Manufacture,Autonomous_Level,CO2_Emissions_g_per_km,Safety_Rating,Units_Sold_2024,Warranty_Years
0,Acura,ZDX (with GM Ultium),2015,Lithium-titanate,55.8,214,CHAdeMO,9.0,111203.94,Matte White,UK,0.0,NaN,5.0,19726,3
1,Lamborghini,Revuelto (PHEV),2025,Lithium-titanate,90.8,212,Vehicle-to-Home (V2H),7.3,127131.65,White,Netherlands,2.0,0.0,4.0,3349,3
2,NIO,ET7,2020,Calcium-ion,64.7,235,Level 2 Charging,8.9,94347.37,Beige,UK,5.0,0.0,5.0,6300,5
3,Audi,e-tron,2025,Lithium-iron phosphate,120.5,140,Ultra-Fast Charging (350 kW+),10.5,75615.15,Sunset Orange,Argentina,2.0,0.0,5.0,2339,5
4,Acura,ZDX (with GM Ultium),2023,Lithium-titanate,51.8,336,Plug-in Hydrogen Refueling,3.6,141046.94,Ice Silver,United Arab Emirates,2.0,0.0,3.0,1051,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3017,Ferrari,SF90 Stradale (PHEV),2018,Sodium-ion,49.9,182,Mobile Charging,11.7,43988.90,Champagne,Indonesia,2.0,0.0,4.0,13366,5
3018,Mahindra,Born Electric (upcoming range),2019,Lithium-ion,136.9,375,Vehicle-to-Home (V2H),5.8,142072.84,Electric Blue,India,NaN,0.0,3.0,15235,3
3019,Cadillac,Lyriq,2021,Lithium-iron phosphate,136.5,221,Plug-in Hydrogen Refueling,1.1,88218.53,Metallic Silver,Canada,2.0,0.0,3.0,13808,3
3020,Mahindra,XUV400,2021,Nickel-metal hydride,96.4,249,Mobile Charging,9.8,110221.30,Matte Green,New Zealand,3.0,NaN,3.0,9854,3
3021,MG,MG4 Electric,2016,Lithium-sulfur,76.2,404,NACS,2.4,148993.26,Matte Black,Austria,5.0,0.0,4.0,5786,5

In [8]:
df.isnull().sum()

Vehicle_ID                  0
Manufacturer                0
Model                       0
Year                        0
Battery_Type                0
Battery_Capacity_kWh        0
Range_km                    0
Charging_Type               0
Charge_Time_hr              0
Price_USD                   0
Color                       0
Country_of_Manufacture      0
Autonomous_Level          442
CO2_Emissions_g_per_km    592
Safety_Rating             337
Units_Sold_2024             0
Warranty_Years              0
dtype: int64

In [9]:
df['Autonomous_Level'].fillna(df['Autonomous_Level'].mean(), inplace=True)

/tmp/ipython-input-2447537745.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Autonomous_Level'].fillna(df['Autonomous_Level'].mean(), inplace=True)

In [10]:
df['CO2_Emissions_g_per_km'].fillna(df['CO2_Emissions_g_per_km'].mean(), inplace=True)

/tmp/ipython-input-3624749414.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CO2_Emissions_g_per_km'].fillna(df['CO2_Emissions_g_per_km'].mean(), inplace=True)

In [11]:
df['Safety_Rating'].fillna(df['Safety_Rating'].mean(), inplace=True)

/tmp/ipython-input-1248112549.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Safety_Rating'].fillna(df['Safety_Rating'].mean(), inplace=True)

In [12]:
df.isnull().sum()

Vehicle_ID                0
Manufacturer              0
Model                     0
Year                      0
Battery_Type              0
Battery_Capacity_kWh      0
Range_km                  0
Charging_Type             0
Charge_Time_hr            0
Price_USD                 0
Color                     0
Country_of_Manufacture    0
Autonomous_Level          0
CO2_Emissions_g_per_km    0
Safety_Rating             0
Units_Sold_2024           0
Warranty_Years            0
dtype: int64

In [13]:
from sklearn import preprocessing

In [15]:
scaler = preprocessing.MinMaxScaler()

In [16]:
Autonomous_Level = df['Autonomous_Level'].values

Autonomous_Level_scaled = scaler.fit_transform(Autonomous_Level.reshape(-1, 1))

In [17]:
df['Autonomous_Level'] = Autonomous_Level_scaled

In [18]:
df['Autonomous_Level']

0       0.000000
1       0.400000
2       1.000000
3       0.400000
4       0.400000
          ...
3017    0.400000
3018    0.503876
3019    0.400000
3020    0.600000
3021    1.000000
Name: Autonomous_Level, Length: 3022, dtype: float64

Titanic csv

In [20]:
import numpy as np
import pandas as pd
import seaborn as sns

In [21]:
url = "https://raw.github.com/mattdelhey/kaggle-titanic/master/Data/train.csv"
titanic = pd.read_csv(url)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   name      891 non-null    object
 3   sex       891 non-null    object
 4   age       714 non-null    float64
 5   sibsp     891 non-null    int64
 6   parch     891 non-null    int64
 7   ticket    891 non-null    object
 8   fare      891 non-null    float64
 9   cabin     204 non-null    object
 10  embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

In [22]:

titanic.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
def woman_child_or_man(passenger):
    age, sex = passenger
    if age < 16:
        return "child"
    else:
        return dict(male="man", female="woman")[sex]

In [24]:
titanic["class"] = titanic.pclass.map({1: "First", 2: "Second", 3: "Third"})
titanic["who"] = titanic[["age", "sex"]].apply(woman_child_or_man, axis=1)
titanic["adult_male"] = titanic.who == "man"
titanic["deck"] = titanic.cabin.str[0].map(lambda s: np.nan if s == "T" else s)
titanic["embark_town"] = titanic.embarked.map({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"})
titanic["alive"] = titanic.survived.map({0: "no", 1: "yes"})
titanic["alone"] = ~(titanic.parch + titanic.sibsp).astype(bool)
titanic = titanic.drop(["name", "ticket", "cabin"], axis=1)

In [25]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [41]:
pal = dict(man="#4682B4", woman="#CD5C5C", child="#2E8B57", male="#6495ED", female="#F08080")

In [28]:
columns = titanic.select_dtypes(include=['object','bool']).columns

In [29]:
columns

Index(['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
ordinal = OrdinalEncoder()

In [32]:
values_cat = ordinal.fit_transform(titanic[columns])

In [33]:
titanic[columns] = values_cat

In [34]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1.0,22.0,1,0,7.2500,2.0,2.0,1.0,1.0,NaN,2.0,0.0,0.0
1,1,1,0.0,38.0,1,0,71.2833,0.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
2,1,3,0.0,26.0,0,0,7.9250,2.0,2.0,2.0,0.0,NaN,2.0,1.0,1.0
3,1,1,0.0,35.0,1,0,53.1000,2.0,0.0,2.0,0.0,2.0,2.0,1.0,0.0
4,0,3,1.0,35.0,0,0,8.0500,2.0,2.0,1.0,1.0,NaN,2.0,0.0,1.0

In [58]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [86]:
x = titanic.drop(['survived','age', 'embarked', 'deck', 'embark_town'], axis=1)
y = titanic['survived']

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
x_train, X_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.3,
                                                    random_state=42)

In [89]:
from sklearn.linear_model import LogisticRegression

In [90]:
model_regression = LogisticRegression()

In [91]:

# Train the model
model_regression.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [92]:
model_regression.coef_

array([[-3.33817527e-01, -5.34558728e-01, -2.00919196e-01,
        -1.45207524e-01,  2.60272519e-03, -3.87653872e-02,
        -3.47639183e-02, -8.75439267e-01,  6.87611823e+00,
        -1.82721413e-01]])

In [93]:
y_predict = model_regression.predict(X_test)

In [94]:
y_predict

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1])

In [95]:
from sklearn.metrics import accuracy_score

In [97]:
accuracy_score(y_test, y_predict)

1.0