In [1]:
import pandas as pd
import numpy as np

# imports

In [2]:
dataset = pd.read_csv('CarPrice_Assignment-68b0d1e70df7d.csv')

# le o csv

In [3]:
dataset.head()

# primeiros registros da tabela

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
dataset.info()

# informações da tabela

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [7]:
columns = dataset.select_dtypes(include=['object','bool']).columns

# pegando todas as var objects e bool para aplicacar ordinal encoder

In [8]:
columns

# printa as colunas

Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber',
       'fuelsystem'],
      dtype='object')

In [12]:
from sklearn.preprocessing import OrdinalEncoder

# importa ordinal encoder

In [13]:
ordinal = OrdinalEncoder()

# pega a var do ordinal encoder

In [14]:
values_cat = ordinal.fit_transform(dataset[columns])

# realizando as transformações nas colunas categoricas

In [15]:
dataset[columns] = values_cat

# seta os novos valores para o dataset

In [16]:
dataset.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1.0,1.0,0.0,1.0,2.0,2.0,0.0,94.5,...,152,5.0,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4.0,1.0,0.0,0.0,3.0,1.0,0.0,99.8,...,109,5.0,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5.0,1.0,0.0,0.0,3.0,0.0,0.0,99.4,...,136,5.0,3.19,3.40,8.0,115,5500,18,22,17450.0

In [20]:
x = dataset.drop(['car_ID', 'symboling', 'CarName', 'price'], axis=1)

# pegando as var independetes x (tudo menos price)

In [21]:
y = dataset['price']

# pegando o price

In [22]:
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split

# importando train test split

In [24]:
x_train, X_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.3,
                                                    random_state=42)

# realizando o split

In [25]:
from sklearn.linear_model import LinearRegression

# importando linear regression

In [26]:
model_regression = LinearRegression()

# pegando a var do linear regression

In [27]:
model_regression.fit(x_train, y_train)

# treinando o modelo

LinearRegression()

In [30]:
model_regression.coef_

# os coeficientes da equação

array([ 7.69686477e+03,  1.23083715e+03, -1.39774178e+03, -1.22327699e+03,
        1.13145240e+03,  1.02780431e+04,  1.43937541e+02, -6.48770192e+01,
        7.80604319e+02,  9.79488185e+01,  1.90777305e+00,  1.86128473e+02,
       -3.90693022e+02,  9.70260903e+01, -3.88146112e+01, -2.34719850e+03,
       -2.20988891e+03,  6.62608815e+02,  2.12867151e+00,  1.59625246e+00,
       -2.59183372e+02,  3.90394201e+01])

In [31]:
y_predict = model_regression.predict(X_test)

# realizando a predição

In [32]:
y_predict

array([24216.15502422, 17006.62712051,  9857.68673151, 13229.28151279,
       24862.45418485,  6253.73268147,  7853.21837566,  7525.29265758,
        9626.87573431,  6488.41867449, 16388.99380842,  7684.93298232,
       16028.50384202, 11215.39922142, 40272.1537962 ,  7653.22233758,
       -3789.83150565, 14493.13343183, 10113.08658242, 10487.7434984 ,
       10912.91515557, 20870.53371429,  7732.82319574,  1032.08334774,
        6904.35465967, 23377.87619154, 14697.07846891, 16374.42605956,
        4943.24591617, 17237.62127266, 25421.91710685,  8085.66064167,
        5139.26787059, 24391.46162024,  8646.54183534, 26021.44371363,
        9996.51348479,  9491.10639063,  5421.1402714 , 14647.08434026,
        8064.79588728, 12853.79156239, 19310.38563819,  5410.10615119,
        6456.45609669, 10277.87341489,  8085.66064167,  7612.73633124,
       17872.77897705, 14393.45212067,  5179.90342379, 20292.97218762,
        2425.1592406 ,  9481.89911824,  4918.44486655, 14174.01500138,
       14704.7095611 ,  9491.10639063, 34585.21900316,  5838.46054462,
        9325.96545755, 21365.25367098])

In [35]:
from sklearn.metrics import mean_absolute_error

# importando o mean squared error

In [36]:
mean_absolute_error(y_test, y_predict)

# calculando o erro

2484.082570992005

In [37]:
from sklearn.metrics import r2_score

# importando o mean squared error

In [38]:
r2_score(y_test, y_predict)

# calculando o erro

0.8012677788261644

In [39]:
dfPeixes = pd.read_csv('Fish-68b0d1e70a8fc.csv')

# le o csv

In [40]:
dfPeixes.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [41]:
pd.unique(dfPeixes['Species'])
# especies dos peixes

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [42]:
dfPeixes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    object
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

In [43]:
dfPeixes.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [44]:
dfPeixes['Species'].value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [45]:
from sklearn.preprocessing import OrdinalEncoder

# importa ordinal encoder

In [46]:
ordinal = OrdinalEncoder()

# pega a var do ordinal encoder

In [50]:
species_cat = dfPeixes['Species']

In [51]:
species_cat = ordinal.fit_transform(species_cat.values.reshape(-1,1))

# transformando as espécies em números

In [52]:
ordinal.categories_[0]

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [53]:
encoding_dict = dict(zip(ordinal.categories_[0], range(len(ordinal.categories_[0]))))

In [54]:
encoding_dict

{'Bream': 0,
 'Parkki': 1,
 'Perch': 2,
 'Pike': 3,
 'Roach': 4,
 'Smelt': 5,
 'Whitefish': 6}

In [55]:
dfPeixes['Species'] = species_cat

In [56]:
dfPeixes

     Species  Weight  Length1  Length2  Length3   Height   Width
0        0.0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0.0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0.0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0.0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0.0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154      5.0    12.2     11.5     12.2     13.4   2.0904  1.3936
155      5.0    13.4     11.7     12.4     13.5   2.4300  1.2690
156      5.0    12.2     12.1     13.0     13.8   2.2770  1.2558
157      5.0    19.7     13.2     14.3     15.2   2.8728  2.0672
158      5.0    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [57]:
x = dfPeixes.drop(['Species'], axis=1)

In [58]:
x

     Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [59]:
y = dfPeixes['Species']

In [60]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
154    5.0
155    5.0
156    5.0
157    5.0
158    5.0
Name: Species, Length: 159, dtype: float64

In [61]:
from sklearn.model_selection import train_test_split

# importando train test split

In [62]:
x_train, X_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.3,
                                                    random_state=42)

# realizando o split

In [63]:
from sklearn.neighbors import KNeighborsClassifier

# importando o KNN

In [64]:
model_knn = KNeighborsClassifier(n_neighbors=3)

# pegando a var do KNN

In [65]:
model_knn.fit(x_train, y_train)

# treinando o modelo

KNeighborsClassifier(n_neighbors=3)

In [66]:
y_predict = model_knn.predict(X_test)

# realizando a predição

In [67]:
y_predict

array([2., 5., 1., 1., 2., 2., 5., 1., 2., 2., 0., 2., 0., 4., 2., 2., 2.,
       1., 0., 2., 5., 0., 0., 0., 0., 2., 4., 1., 5., 5., 0., 1., 1., 0.,
       0., 1., 4., 1., 2., 2., 0., 0., 5., 2., 4., 1., 4., 0.])

In [68]:
from sklearn.metrics import accuracy_score

# importando o accuracy score

In [69]:
accuracy_score(y_test, y_predict)

# calculando a acurácia

0.4791666666666667

In [73]:
list_result = list()
# percorrendo uma lista n vizinhos de 1 até 100 com passo de 3
for n_knn in range(1, 100, 2):
    model_knn = KNeighborsClassifier(n_neighbors=n_knn)
    model_knn.fit(x_train, y_train)
    y_predict = model_knn.predict(X_test)
    acc = accuracy_score(y_test, y_predict)
    list_result.append((acc, n_knn))

In [74]:
dfPeixes_result = pd.DataFrame(list_result, columns=['accuracy', 'n_neighbors'])

In [75]:
dfPeixes_result

    accuracy  n_neighbors
0   0.479167            1
1   0.479167            3
2   0.583333            5
3   0.604167            7
4   0.604167            9
5   0.562500           11
6   0.520833           13
7   0.562500           15
8   0.541667           17
9   0.520833           19
10  0.500000           21
11  0.520833           23
12  0.437500           25
13  0.437500           27
14  0.500000           29
15  0.500000           31
16  0.500000           33
17  0.500000           35
18  0.500000           37
19  0.520833           39
20  0.500000           41
21  0.479167           43
22  0.479167           45
23  0.479167           47
24  0.479167           49
25  0.479167           51
26  0.479167           53
27  0.479167           55
28  0.479167           57
29  0.479167           59
30  0.375000           61
31  0.354167           63
32  0.291667           65
33  0.291667           67
34  0.291667           69
35  0.291667           71
36  0.291667           73
37  0.291667           75
38  0.291667           77
39  0.291667           79
40  0.291667           81
41  0.291667           83
42  0.291667           85
43  0.291667           87
44  0.291667           89
45  0.291667           91
46  0.291667           93
47  0.291667           95
48  0.291667           97
49  0.291667           99