In [1]:
import pandas as pd
import numpy as np

In [3]:
# leitura csv
df = pd.read_csv('titanic.csv', index_col=False)

In [5]:
# exibe alguns dados do começo da lista

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
# observando as colunas

df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df['Age'].min()

0.42

In [8]:
df['Age'].max()

80.0

In [9]:
df.drop(['Name', 'Ticket', 'SibSp', 'Parch', 'Cabin'], axis=1, inplace=True)

# deletando colunas

In [10]:
df

     PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0              1         0       3    male  22.0   7.2500        S
1              2         1       1  female  38.0  71.2833        C
2              3         1       3  female  26.0   7.9250        S
3              4         1       1  female  35.0  53.1000        S
4              5         0       3    male  35.0   8.0500        S
..           ...       ...     ...     ...   ...      ...      ...
886          887         0       2    male  27.0  13.0000        S
887          888         1       1  female  19.0  30.0000        S
888          889         0       3  female   NaN  23.4500        S
889          890         1       1    male  26.0  30.0000        C
890          891         0       3    male  32.0   7.7500        Q

[891 rows x 7 columns]

In [12]:
df.isnull().sum()

# limpar a tabela antes de trabalhar com ela para processamento de dados

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
Embarked         2
dtype: int64

In [13]:
df['Embarked'].fillna('S', inplace=True)

# deletando as linhas com valores nulos

/tmp/ipython-input-2889471567.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna('S', inplace=True)

In [14]:
df['Age'].mean()

# valor médio para a col age

np.float64(29.69911764705882)

In [15]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

# prenche os valores nulos de age com a média }

/tmp/ipython-input-1296056691.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [16]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       0
dtype: int64

In [17]:
from sklearn import preprocessing

In [18]:
scaler = preprocessing.StandardScaler()

In [19]:
fare = df['Fare'].values

# pega os valores da col Fare

In [20]:
fare

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.05  ,
         8.05  ,   7.8542,  61.175 ,  20.575 ,   7.25  ,   8.05  ,
        34.6542,  63.3583,  23.    ,  26.    ,   7.8958,   7.8958,
        77.2875,   8.6542,   7.925 ,   7.8958,   7.65  ,   7.775 ,
         7.8958,  24.15  ,  52.    ,  14.4542,   8.05  ,   9.825 ,
        14.4583,   7.925 ,   7.75  ,  21.    , 247.5208,  31.275 ,
        73.5   ,   8.05  ,  30.0708,  13.    ,  77.2875,  11.2417,
         7.75  ,   7.1417,  22.3583,   6.975 ,   7.8958,   7.05  ,
        14.5   ,  26.    ,  13.    ,  15.0458,  26.2833,  53.1   ,
         9.2167,  79.2   ,  15.2458,   7.75  ,  15.85  ,   6.75  ,
        11.5   ,  36.75  ,   7.7958,  34.375 ,  26.    ,  13.    ,
        12.525 ,  66.6   ,   8.05  ,  14.5   ,   7.3125,  61.3792,
         7.7333,   8.05  ,   8.6625,  69.55  ,  16.1   ,  15.75  ,
         7.775 ,   8.6625,  39.6875,  20.525 ,  55.    ,  27.9   ,
        25.925 ,  56.4958,  33.5   ,  29.125 ,  11.1333,   7.925 ,
        30.6958,   7.8542,  25.4667,  28.7125,  13.    ,   0.    ,
        69.55  ,  15.05  ,  31.3875,  39.    ,  22.025 ,  50.    ,
        15.5   ,  26.55  ,  15.5   ,   7.8958,  13.    ,  13.    ,
         7.8542,  26.    ,  27.7208, 146.5208,   7.75  ,   8.4042,
         7.75  ,  13.    ,   9.5   ,  69.55  ,   6.4958,   7.225 ,
         8.05  ,  10.4625,  15.85  ,  18.7875,   7.75  ,  31.    ,
         7.05  ,  21.    ,   7.25  ,  13.    ,   7.75  , 113.275 ,
         7.925 ,  27.    ,  76.2917,  10.5   ,   8.05  ,  13.    ,
         8.05  ,   7.8958,  90.    ,   9.35  ,  10.5   ,   7.25  ,
        13.    ,  25.4667,  83.475 ,   7.775 ,  13.5   ,  31.3875,
        10.5   ,   7.55  ,  26.    ,  26.25  ,  10.5   ,  12.275 ,
        14.4542,  15.5   ,  10.5   ,   7.125 ,   7.225 ,  90.    ,
         7.775 ,  14.5   ,  52.5542,  26.    ,   7.25  ,  10.4625,
        26.55  ,  16.1   ,  20.2125,  15.2458,  79.2   ,  86.5   ,
       512.3292,  26.    ,   7.75  ,  31.3875,  79.65  ,   0.    ,
         7.75  ,  10.5   ,  39.6875,   7.775 , 153.4625, 135.6333,
        31.    ,   0.    ,  19.5   ,  29.7   ,   7.75  ,  77.9583,
         7.75  ,   0.    ,  29.125 ,  20.25  ,   7.75  ,   7.8542,
         9.5   ,   8.05  ,  26.    ,   8.6625,   9.5   ,   7.8958,
        13.    ,   7.75  ,  78.85  ,  91.0792,  12.875 ,   8.85  ,
         7.8958,  27.7208,   7.2292, 151.55  ,  30.5   , 247.5208,
         7.75  ,  23.25  ,   0.    ,  12.35  ,   8.05  , 151.55  ,
       110.8833, 108.9   ,  24.    ,  56.9292,  83.1583, 262.375 ,
        26.    ,   7.8958,  26.25  ,   7.8542,  26.    ,  14.    ,
       164.8667, 134.5   ,   7.25  ,   7.8958,  12.35  ,  29.    ,
        69.55  , 135.6333,   6.2375,  13.    ,  20.525 ,  57.9792,
        23.25  ,  28.5   , 153.4625,  18.    , 133.65  ,   7.8958,
        66.6   , 134.5   ,   8.05  ,  35.5   ,  26.    , 263.    ,
        13.    ,  13.    ,  13.    ,  13.    ,  13.    ,  16.1   ,
        15.9   ,   8.6625,   9.225 ,  35.    ,   7.2292,  17.8   ,
         7.225 ,   9.5   ,  55.    ,  13.    ,   7.8792,   7.8792,
        27.9   ,  27.7208,  14.4542,   7.05  ,  15.5   ,   7.25  ,
        75.25  ,   7.2292,   7.75  ,  69.3   ,  55.4417,   6.4958,
         8.05  , 135.6333,  21.075 ,  82.1708,   7.25  , 211.5   ,
         4.0125,   7.775 , 227.525 ,  15.7417,   7.925 ,  52.    ,
         7.8958,  73.5   ,  46.9   ,  13.    ,   7.7292,  12.    ,
       120.    ,   7.7958,   7.925 , 113.275 ,  16.7   ,   7.7958,
         7.8542,  26.    ,  10.5   ,  12.65  ,   7.925 ,   8.05  ,
         9.825 ,  15.85  ,   8.6625,  21.    ,   7.75  ,  18.75  ,
         7.775 ,  25.4667,   7.8958,   6.8583,  90.    ,   0.    ,
         7.925 ,   8.05  ,  32.5   ,  13.    ,  13.    ,  24.15  ,
         7.8958,   7.7333,   7.875 ,  14.4   ,  20.2125,   7.25  ,
        26.    ,  26.    ,   7.75  ,   8.05  ,  26.55  ,  16.1   ,
        26.    ,   7.125 ,  55.9   , 120.    ,  34.375 ,  18.75  ,
       263.    ,  10.5   ,  26.25  ,   9.5   ,   7.775 ,  13.    ,
         8.1125,  81.8583,  19.5   ,  26.55  ,  19.2583,  30.5   ,
        27.75  ,  19.9667,  27.75  ,  89.1042,   8.05  ,   7.8958,
        26.55  ,  51.8625,  10.5   ,   7.75  ,  26.55  ,   8.05  ,
        38.5   ,  13.    ,   8.05  ,   7.05  ,   0.    ,  26.55  ,
         7.725 ,  19.2583,   7.25  ,   8.6625,  27.75  ,  13.7917,
         9.8375,  52.    ,  21.    ,   7.0458,   7.5208,  12.2875,
        46.9   ,   0.    ,   8.05  ,   9.5875,  91.0792,  25.4667,
        90.    ,  29.7   ,   8.05  ,  15.9   ,  19.9667,   7.25  ,
        30.5   ,  49.5042,   8.05  ,  14.4583,  78.2667,  15.1   ,
       151.55  ,   7.7958,   8.6625,   7.75  ,   7.6292,   9.5875,
        86.5   , 108.9   ,  26.    ,  26.55  ,  22.525 ,  56.4958,
         7.75  ,   8.05  ,  26.2875,  59.4   ,   7.4958,  34.0208,
        10.5   ,  24.15  ,  26.    ,   7.8958,  93.5   ,   7.8958,
         7.225 ,  57.9792,   7.2292,   7.75  ,  10.5   , 221.7792,
         7.925 ,  11.5   ,  26.    ,   7.2292,   7.2292,  22.3583,
         8.6625,  26.25  ,  26.55  , 106.425 ,  14.5   ,  49.5   ,
        71.    ,  31.275 ,  31.275 ,  26.    , 106.425 ,  26.    ,
        26.    ,  13.8625,  20.525 ,  36.75  , 110.8833,  26.    ,
         7.8292,   7.225 ,   7.775 ,  26.55  ,  39.6   , 227.525 ,
        79.65  ,  17.4   ,   7.75  ,   7.8958,  13.5   ,   8.05  ,
         8.05  ,  24.15  ,   7.8958,  21.075 ,   7.2292,   7.8542,
        10.5   ,  51.4792,  26.3875,   7.75  ,   8.05  ,  14.5   ,
        13.    ,  55.9   ,  14.4583,   7.925 ,  30.    , 110.8833,
        26.    ,  40.125 ,   8.7125,  79.65  ,  15.    ,  79.2   ,
         8.05  ,   8.05  ,   7.125 ,  78.2667,   7.25  ,   7.75  ,
        26.    ,  24.15  ,  33.    ,   0.    ,   7.225 ,  56.9292,
        27.    ,   7.8958,  42.4   ,   8.05  ,  26.55  ,  15.55  ,
         7.8958,  30.5   ,  41.5792, 153.4625,  31.275 ,   7.05  ,
        15.5   ,   7.75  ,   8.05  ,  65.    ,  14.4   ,  16.1   ,
        39.    ,  10.5   ,  14.4542,  52.5542,  15.7417,   7.8542,
        16.1   ,  32.3208,  12.35  ,  77.9583,   7.8958,   7.7333,
        30.    ,   7.0542,  30.5   ,   0.    ,  27.9   ,  13.    ,
         7.925 ,  26.25  ,  39.6875,  16.1   ,   7.8542,  69.3   ,
        27.9   ,  56.4958,  19.2583,  76.7292,   7.8958,  35.5   ,
         7.55  ,   7.55  ,   7.8958,  23.    ,   8.4333,   7.8292,
         6.75  ,  73.5   ,   7.8958,  15.5   ,  13.    , 113.275 ,
       133.65  ,   7.225 ,  25.5875,   7.4958,   7.925 ,  73.5   ,
        13.    ,   7.775 ,   8.05  ,  52.    ,  39.    ,  52.    ,
        10.5   ,  13.    ,   0.    ,   7.775 ,   8.05  ,   9.8417,
        46.9   , 512.3292,   8.1375,  76.7292,   9.225 ,  46.9   ,
        39.    ,  41.5792,  39.6875,  10.1708,   7.7958, 211.3375,
        57.    ,  13.4167,  56.4958,   7.225 ,  26.55  ,  13.5   ,
         8.05  ,   7.7333, 110.8833,   7.65  , 227.525 ,  26.2875,
        14.4542,   7.7417,   7.8542,  26.    ,  13.5   ,  26.2875,
       151.55  ,  15.2458,  49.5042,  26.55  ,  52.    ,   9.4833,
        13.    ,   7.65  , 227.525 ,  10.5   ,  15.5   ,   7.775 ,
        33.    ,   7.0542,  13.    ,  13.    ,  53.1   ,   8.6625,
        21.    ,   7.7375,  26.    ,   7.925 , 211.3375,  18.7875,
         0.    ,  13.    ,  13.    ,  16.1   ,  34.375 , 512.3292,
         7.8958,   7.8958,  30.    ,  78.85  , 262.375 ,  16.1   ,
         7.925 ,  71.    ,  20.25  ,  13.    ,  53.1   ,   7.75  ,
        23.    ,  12.475 ,   9.5   ,   7.8958,  65.    ,  14.5   ,
         7.7958,  11.5   ,   8.05  ,  86.5   ,  14.5   ,   7.125 ,
         7.2292, 120.    ,   7.775 ,  77.9583,  39.6   ,   7.75  ,
        24.15  ,   8.3625,   9.5   ,   7.8542,  10.5   ,   7.225 ,
        23.    ,   7.75  ,   7.75  ,  12.475 ,   7.7375, 211.3375,
         7.2292,  57.    ,  30.    ,  23.45  ,   7.05  ,   7.25  ,
         7.4958,  29.125 ,  20.575 ,  79.2   ,   7.75  ,  26.    ,
        69.55  ,  30.6958,   7.8958,  13.    ,  25.9292,   8.6833,
         7.2292,  24.15  ,  13.    ,  26.25  , 120.    ,   8.5167,
         6.975 ,   7.775 ,   0.    ,   7.775 ,  13.    ,  53.1   ,
         7.8875,  24.15  ,  10.5   ,  31.275 ,   8.05  ,   0.    ,
         7.925 ,  37.0042,   6.45  ,  27.9   ,  93.5   ,   8.6625,
         0.    ,  12.475 ,  39.6875,   6.95  ,  56.4958,  37.0042,
         7.75  ,  80.    ,  14.4542,  18.75  ,   7.2292,   7.8542,
         8.3   ,  83.1583,   8.6625,   8.05  ,  56.4958,  29.7   ,
         7.925 ,  10.5   ,  31.    ,   6.4375,   8.6625,   7.55  ,
        69.55  ,   7.8958,  33.    ,  89.1042,  31.275 ,   7.775 ,
        15.2458,  39.4   ,  26.    ,   9.35  , 164.8667,  26.55  ,
        19.2583,   7.2292,  14.1083,  11.5   ,  25.9292,  69.55  ,
        13.    ,  13.    ,  13.8583,  50.4958,   9.5   ,  11.1333,
         7.8958,  52.5542,   5.    ,   9.    ,  24.    ,   7.225 ,
         9.8458,   7.8958,   7.8958,  83.1583,  26.    ,   7.8958,
        10.5167,  10.5   ,   7.05  ,  29.125 ,  13.    ,  30.    ,
        23.45  ,  30.    ,   7.75  ])

In [21]:
fare_scaled = scaler.fit_transform(fare.reshape(-1, 1))

# transforma os dados entre valores de -1 a 1

In [22]:
fare_scaled

array([[-5.02445171e-01],
       [ 7.86845294e-01],
       [-4.88854258e-01],
       [ 4.20730236e-01],
       [-4.86337422e-01],
       [-4.78116429e-01],
       [ 3.95813561e-01],
       [-2.24083121e-01],
       [-4.24256141e-01],
       [-4.29555021e-02],
       [-3.12172378e-01],
       [-1.13845709e-01],
       [-4.86337422e-01],
       [-1.87093118e-02],
       [-4.90279793e-01],
       [-3.26266659e-01],
       [-6.19988892e-02],
       [-3.86670720e-01],
       [-2.85997284e-01],
       [-5.02948539e-01],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-4.86756223e-01],
       [ 6.63597416e-02],
       [-2.24083121e-01],
       [-1.64441595e-02],
       [-5.02948539e-01],
       [ 4.64700108e+00],
       [-4.89776426e-01],
       [-4.89442190e-01],
       [-9.02720170e-02],
       [ 2.30172882e+00],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 1.00606170e+00],
       [ 3.98582080e-01],
       [-5.02863973e-01],
       [-4.86337422e-01],
       [-2.85997284e-01],
       [-4.22073541e-01],
       [-4.57645492e-01],
       [-2.25593223e-01],
       [-4.89442190e-01],
       [ 1.88762532e-01],
       [-4.89776426e-01],
       [-4.86337422e-01],
       [-3.36334002e-01],
       [-4.92377828e-01],
       [-2.11917743e-01],
       [-2.90024222e-01],
       [ 1.50673744e-01],
       [-4.91371093e-01],
       [ 8.96496787e-01],
       [-1.24919787e-01],
       [ 5.99510151e-01],
       [ 6.63597416e-02],
       [-4.37007438e-01],
       [-5.02863973e-01],
       [-8.96840841e-02],
       [ 2.95895176e-01],
       [-5.02863973e-01],
       [ 9.62353321e-01],
       [ 1.03232136e+00],
       [-8.66638810e-02],
       [-9.02720170e-02],
       [-3.41452240e-01],
       [-4.37007438e-01],
       [-4.84156835e-01],
       [-4.88854258e-01],
       [-4.74004926e-01],
       [-4.37007438e-01],
       [ 2.95895176e-01],
       [ 8.31477855e-01],
       [-3.57390858e-01],
       [ 4.89103607e-01],
       [-4.94391297e-01],
       [-4.89442190e-01],
       [-4.86337422e-01],
       [-6.45157251e-02],
       [-3.97241431e-01],
       [-4.67209469e-01],
       [-4.57142125e-01],
       [-4.91622777e-01],
       [ 2.99922113e-01],
       [-4.37007438e-01],
       [-3.29286862e-01],
       [ 4.37082185e-02],
       [-4.86337422e-01],
       [ 4.64700108e+00],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-4.90279793e-01],
       [ 5.83317835e-01],
       [-2.34150465e-01],
       [-5.02445171e-01],
       [-4.86337422e-01],
       [ 4.93298232e-02],
       [ 6.27277898e-01],
       [-1.85323848e-01],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [-4.89442190e-01],
       [ 9.07737982e-01],
       [-4.74172044e-01],
       [-4.88854258e-01],
       [-4.89442190e-01],
       [-4.94391297e-01],
       [-4.91874461e-01],
       [-4.89442190e-01],
       [-1.62168958e-01],
       [ 3.98582080e-01],
       [-3.57390858e-01],
       [-4.86337422e-01],
       [-4.50598352e-01],
       [-3.57308306e-01],
       [-4.88854258e-01],
       [-4.92377828e-01],
       [-2.25593223e-01],
       [ 4.33533223e+00],
       [-1.87093118e-02],
       [ 8.31477855e-01],
       [-4.86337422e-01],
       [-4.29555021e-02],
       [-3.86670720e-01],
       [ 9.07737982e-01],
       [-4.22073541e-01],
       [-4.92377828e-01],
       [-5.04625758e-01],
       [-1.98244277e-01],
       [-5.07982210e-01],
       [-4.89442190e-01],
       [-5.06472109e-01],
       [-3.56468689e-01],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-3.45479177e-01],
       [-1.19215630e-01],
       [ 4.20730236e-01],
       [-4.62846282e-01],
       [ 9.46245572e-01],
       [-3.41452240e-01],
       [-4.92377828e-01],
       [-3.29286862e-01],
       [-5.12512515e-01],
       [-4.16872751e-01],
       [ 9.15281006e-02],
       [-4.91455659e-01],
       [ 4.37082185e-02],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-3.96234697e-01],
       [ 6.92548513e-01],
       [-4.86337422e-01],
       [-3.56468689e-01],
       [-5.01186753e-01],
       [ 5.87429338e-01],
       [-4.92714077e-01],
       [-4.86337422e-01],
       [-4.74004926e-01],
       [ 7.51945840e-01],
       [-3.24253190e-01],
       [-3.31300330e-01],
       [-4.91874461e-01],
       [-4.74004926e-01],
       [ 1.50673744e-01],
       [-2.35157199e-01],
       [ 4.58986142e-01],
       [-8.66638810e-02],
       [-1.26429888e-01],
       [ 4.89103607e-01],
       [ 2.60903672e-02],
       [-6.19988892e-02],
       [-4.24256141e-01],
       [-4.88854258e-01],
       [-3.03713226e-02],
       [-4.90279793e-01],
       [-1.35657615e-01],
       [-7.03044477e-02],
       [-3.86670720e-01],
       [-6.48421654e-01],
       [ 7.51945840e-01],
       [-3.45394611e-01],
       [-1.64441595e-02],
       [ 1.36831147e-01],
       [-2.04955168e-01],
       [ 3.58312706e-01],
       [-3.36334002e-01],
       [-1.13845709e-01],
       [-3.36334002e-01],
       [-4.89442190e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-9.02720170e-02],
       [ 2.30172882e+00],
       [-4.92377828e-01],
       [-4.79205715e-01],
       [-4.92377828e-01],
       [-3.86670720e-01],
       [-4.57142125e-01],
       [ 7.51945840e-01],
       [-5.17630753e-01],
       [-5.02948539e-01],
       [-4.86337422e-01],
       [-4.37762489e-01],
       [-3.29286862e-01],
       [-2.70141218e-01],
       [-4.92377828e-01],
       [-2.42463508e-02],
       [-5.06472109e-01],
       [-2.25593223e-01],
       [-5.02445171e-01],
       [-3.86670720e-01],
       [-4.92377828e-01],
       [ 1.63233504e+00],
       [-4.88854258e-01],
       [-1.04785100e-01],
       [ 8.87687861e-01],
       [-4.37007438e-01],
       [-4.86337422e-01],
       [-3.86670720e-01],
       [-4.86337422e-01],
       [-4.89442190e-01],
       [ 1.16370019e+00],
       [-4.60162328e-01],
       [-4.37007438e-01],
       [-5.02445171e-01],
       [-3.86670720e-01],
       [-1.35657615e-01],
       [ 1.03232136e+00],
       [-4.91874461e-01],
       [-3.76603377e-01],
       [-1.64441595e-02],
       [-4.37007438e-01],
       [-4.96404765e-01],
       [-1.24919787e-01],
       [-1.19886115e-01],
       [-4.37007438e-01],
       [-4.01268368e-01],
       [-3.57390858e-01],
       [-3.36334002e-01],
       [-4.37007438e-01],
       [-5.04962007e-01],
       [-5.02948539e-01],
       [ 1.16370019e+00],
       [-4.91874461e-01],
       [-3.56468689e-01],
       [ 4.09740724e-01],
       [-1.24919787e-01],
       [-5.02445171e-01],
       [-4.37762489e-01],
       [-1.13845709e-01],
       [-3.24253190e-01],
       [-2.41449289e-01],
       [-3.41452240e-01],
       [ 9.46245572e-01],
       [ 1.09322879e+00],
       [ 9.66716653e+00],
       [-1.24919787e-01],
       [-4.92377828e-01],
       [-1.64441595e-02],
       [ 9.55306181e-01],
       [-6.48421654e-01],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 1.50673744e-01],
       [-4.91874461e-01],
       [ 2.44149778e+00],
       [ 2.08251241e+00],
       [-2.42463508e-02],
       [-6.48421654e-01],
       [-2.55795253e-01],
       [-5.04214441e-02],
       [-4.92377828e-01],
       [ 9.21244331e-01],
       [-4.92377828e-01],
       [-6.48421654e-01],
       [-6.19988892e-02],
       [-2.40694238e-01],
       [-4.92377828e-01],
       [-4.90279793e-01],
       [-4.57142125e-01],
       [-4.86337422e-01],
       [-1.24919787e-01],
       [-4.74004926e-01],
       [-4.57142125e-01],
       [-4.89442190e-01],
       [-3.86670720e-01],
       [-4.92377828e-01],
       [ 9.39198431e-01],
       [ 1.18542955e+00],
       [-3.89187556e-01],
       [-4.70229672e-01],
       [-4.89442190e-01],
       [-9.02720170e-02],
       [-5.02863973e-01],
       [ 2.40299019e+00],
       [-3.43136943e-02],
       [ 4.33533223e+00],
       [-4.92377828e-01],
       [-1.80290176e-01],
       [-6.48421654e-01],
       [-3.99758267e-01],
       [-4.86337422e-01],
       [ 2.40299019e+00],
       [ 1.58417891e+00],
       [ 1.54424578e+00],
       [-1.65189161e-01],
       [ 4.97829980e-01],
       [ 1.02594470e+00],
       [ 4.63441690e+00],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [-1.19886115e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-3.66536033e-01],
       [ 2.67111778e+00],
       [ 2.05969377e+00],
       [-5.02445171e-01],
       [-4.89442190e-01],
       [-3.99758267e-01],
       [-6.45157251e-02],
       [ 7.51945840e-01],
       [ 2.08251241e+00],
       [-5.22831542e-01],
       [-3.86670720e-01],
       [-2.35157199e-01],
       [ 5.18971402e-01],
       [-1.80290176e-01],
       [-7.45830687e-02],
       [ 2.44149778e+00],
       [-2.85997284e-01],
       [ 2.04257929e+00],
       [-4.89442190e-01],
       [ 6.92548513e-01],
       [ 2.05969377e+00],
       [-4.86337422e-01],
       [ 6.63597416e-02],
       [-1.24919787e-01],
       [ 4.64700108e+00],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.24253190e-01],
       [-3.28280127e-01],
       [-4.74004926e-01],
       [-4.62679164e-01],
       [ 5.62923980e-02],
       [-5.02863973e-01],
       [-2.90024222e-01],
       [-5.02948539e-01],
       [-4.57142125e-01],
       [ 4.58986142e-01],
       [-3.86670720e-01],
       [-4.89776426e-01],
       [-4.89776426e-01],
       [-8.66638810e-02],
       [-9.02720170e-02],
       [-3.57390858e-01],
       [-5.06472109e-01],
       [-3.36334002e-01],
       [-5.02445171e-01],
       [ 8.66713557e-01],
       [-5.02863973e-01],
       [-4.92377828e-01],
       [ 7.46912168e-01],
       [ 4.67879633e-01],
       [-5.17630753e-01],
       [-4.86337422e-01],
       [ 2.08251241e+00],
       [-2.24083121e-01],
       [ 1.00606170e+00],
       [-5.02445171e-01],
       [ 3.61006469e+00],
       [-5.67631221e-01],
       [-4.91874461e-01],
       [ 3.93272305e+00],
       [-3.31467448e-01],
       [-4.88854258e-01],
       [ 3.98582080e-01],
       [-4.89442190e-01],
       [ 8.31477855e-01],
       [ 2.95895176e-01],
       [-3.86670720e-01],
       [-4.92796629e-01],
       [-4.06805407e-01],
       [ 1.76774081e+00],
       [-4.91455659e-01],
       [-4.88854258e-01],
       [ 1.63233504e+00],
       [-3.12172378e-01],
       [-4.91455659e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-4.37007438e-01],
       [-3.93717861e-01],
       [-4.88854258e-01],
       [-4.86337422e-01],
       [-4.50598352e-01],
       [-3.29286862e-01],
       [-4.74004926e-01],
       [-2.25593223e-01],
       [-4.92377828e-01],
       [-2.70896269e-01],
       [-4.91874461e-01],
       [-1.35657615e-01],
       [-4.89442190e-01],
       [-5.10331928e-01],
       [ 1.16370019e+00],
       [-6.48421654e-01],
       [-4.88854258e-01],
       [-4.86337422e-01],
       [ 5.95568003e-03],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-1.62168958e-01],
       [-4.89442190e-01],
       [-4.92714077e-01],
       [-4.89860992e-01],
       [-3.58482158e-01],
       [-2.41449289e-01],
       [-5.02445171e-01],
       [-1.24919787e-01],
       [-1.24919787e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-1.13845709e-01],
       [-3.24253190e-01],
       [-1.24919787e-01],
       [-5.04962007e-01],
       [ 4.77107360e-01],
       [ 1.76774081e+00],
       [ 4.37082185e-02],
       [-2.70896269e-01],
       [ 4.64700108e+00],
       [-4.37007438e-01],
       [-1.19886115e-01],
       [-4.57142125e-01],
       [-4.91874461e-01],
       [-3.86670720e-01],
       [-4.85079004e-01],
       [ 9.99769611e-01],
       [-2.55795253e-01],
       [-1.13845709e-01],
       [-2.60661807e-01],
       [-3.43136943e-02],
       [-8.96840841e-02],
       [-2.46398395e-01],
       [-8.96840841e-02],
       [ 1.14566354e+00],
       [-4.86337422e-01],
       [-4.89442190e-01],
       [-1.13845709e-01],
       [ 3.95813561e-01],
       [-4.37007438e-01],
       [-4.92377828e-01],
       [-1.13845709e-01],
       [-4.86337422e-01],
       [ 1.26763803e-01],
       [-3.86670720e-01],
       [-4.86337422e-01],
       [-5.06472109e-01],
       [-6.48421654e-01],
       [-1.13845709e-01],
       [-4.92881195e-01],
       [-2.60661807e-01],
       [-5.02445171e-01],
       [-4.74004926e-01],
       [-8.96840841e-02],
       [-3.70730088e-01],
       [-4.50346668e-01],
       [ 3.98582080e-01],
       [-2.25593223e-01],
       [-5.06556675e-01],
       [-4.96992698e-01],
       [-4.01016685e-01],
       [ 2.95895176e-01],
       [-6.48421654e-01],
       [-4.86337422e-01],
       [-4.55380340e-01],
       [ 1.18542955e+00],
       [-1.35657615e-01],
       [ 1.16370019e+00],
       [-5.04214441e-02],
       [-4.86337422e-01],
       [-3.28280127e-01],
       [-2.46398395e-01],
       [-5.02445171e-01],
       [-3.43136943e-02],
       [ 3.48329928e-01],
       [-4.86337422e-01],
       [-3.57308306e-01],
       [ 9.27453868e-01],
       [-3.44387877e-01],
       [ 2.40299019e+00],
       [-4.91455659e-01],
       [-4.74004926e-01],
       [-4.92377828e-01],
       [-4.94810098e-01],
       [-4.55380340e-01],
       [ 1.09322879e+00],
       [ 1.54424578e+00],
       [-1.24919787e-01],
       [-1.13845709e-01],
       [-1.94887825e-01],
       [ 4.89103607e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-1.19131064e-01],
       [ 5.47578765e-01],
       [-4.97496065e-01],
       [ 3.65765123e-02],
       [-4.37007438e-01],
       [-1.62168958e-01],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [ 1.23417160e+00],
       [-4.89442190e-01],
       [-5.02948539e-01],
       [ 5.18971402e-01],
       [-5.02863973e-01],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 3.81703316e+00],
       [-4.88854258e-01],
       [-4.16872751e-01],
       [-1.24919787e-01],
       [-5.02863973e-01],
       [-5.02863973e-01],
       [-1.98244277e-01],
       [-4.74004926e-01],
       [-1.19886115e-01],
       [-1.13845709e-01],
       [ 1.49441243e+00],
       [-3.56468689e-01],
       [ 3.48245362e-01],
       [ 7.81141137e-01],
       [-1.87093118e-02],
       [-1.87093118e-02],
       [-1.24919787e-01],
       [ 1.49441243e+00],
       [-1.24919787e-01],
       [-1.24919787e-01],
       [-3.69304552e-01],
       [-2.35157199e-01],
       [ 9.15281006e-02],
       [ 1.58417891e+00],
       [-1.24919787e-01],
       [-4.90783161e-01],
       [-5.02948539e-01],
       [-4.91874461e-01],
       [-1.13845709e-01],
       [ 1.48911959e-01],
       [ 3.93272305e+00],
       [ 9.55306181e-01],
       [-2.98078096e-01],
       [-4.92377828e-01],
       [-4.89442190e-01],
       [-3.76603377e-01],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-1.62168958e-01],
       [-4.89442190e-01],
       [-2.24083121e-01],
       [-5.02863973e-01],
       [-4.90279793e-01],
       [-4.37007438e-01],
       [ 3.88095935e-01],
       [-1.17117595e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-3.56468689e-01],
       [-3.86670720e-01],
       [ 4.77107360e-01],
       [-3.57308306e-01],
       [-4.88854258e-01],
       [-4.43810379e-02],
       [ 1.58417891e+00],
       [-1.24919787e-01],
       [ 1.59482670e-01],
       [-4.72998191e-01],
       [ 9.55306181e-01],
       [-3.46401346e-01],
       [ 9.46245572e-01],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-5.04962007e-01],
       [ 9.27453868e-01],
       [-5.02445171e-01],
       [-4.92377828e-01],
       [-1.24919787e-01],
       [-1.62168958e-01],
       [ 1.60230236e-02],
       [-6.48421654e-01],
       [-5.02948539e-01],
       [ 4.97829980e-01],
       [-1.04785100e-01],
       [-4.89442190e-01],
       [ 2.05289083e-01],
       [-4.86337422e-01],
       [-1.13845709e-01],
       [-3.35327268e-01],
       [-4.89442190e-01],
       [-3.43136943e-02],
       [ 1.88762532e-01],
       [ 2.44149778e+00],
       [-1.87093118e-02],
       [-5.06472109e-01],
       [-3.36334002e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [ 6.60333014e-01],
       [-3.58482158e-01],
       [-3.24253190e-01],
       [ 1.36831147e-01],
       [-4.37007438e-01],
       [-3.57390858e-01],
       [ 4.09740724e-01],
       [-3.31467448e-01],
       [-4.90279793e-01],
       [-3.24253190e-01],
       [ 2.34754408e-03],
       [-3.99758267e-01],
       [ 9.21244331e-01],
       [-4.89442190e-01],
       [-4.92714077e-01],
       [-4.43810379e-02],
       [-5.06387543e-01],
       [-3.43136943e-02],
       [-6.48421654e-01],
       [-8.66638810e-02],
       [-3.86670720e-01],
       [-4.88854258e-01],
       [-1.19886115e-01],
       [ 1.50673744e-01],
       [-3.24253190e-01],
       [-4.90279793e-01],
       [ 7.46912168e-01],
       [-8.66638810e-02],
       [ 4.89103607e-01],
       [-2.60661807e-01],
       [ 8.96496787e-01],
       [-4.89442190e-01],
       [ 6.63597416e-02],
       [-4.96404765e-01],
       [-4.96404765e-01],
       [-4.89442190e-01],
       [-1.85323848e-01],
       [-4.78619796e-01],
       [-4.90783161e-01],
       [-5.12512515e-01],
       [ 8.31477855e-01],
       [-4.89442190e-01],
       [-3.36334002e-01],
       [-3.86670720e-01],
       [ 1.63233504e+00],
       [ 2.04257929e+00],
       [-5.02948539e-01],
       [-1.33225345e-01],
       [-4.97496065e-01],
       [-4.88854258e-01],
       [ 8.31477855e-01],
       [-3.86670720e-01],
       [-4.91874461e-01],
       [-4.86337422e-01],
       [ 3.98582080e-01],
       [ 1.36831147e-01],
       [ 3.98582080e-01],
       [-4.37007438e-01],
       [-3.86670720e-01],
       [-6.48421654e-01],
       [-4.91874461e-01],
       [-4.86337422e-01],
       [-4.50262103e-01],
       [ 2.95895176e-01],
       [ 9.66716653e+00],
       [-4.84575637e-01],
       [ 8.96496787e-01],
       [-4.62679164e-01],
       [ 2.95895176e-01],
       [ 1.36831147e-01],
       [ 1.88762532e-01],
       [ 1.50673744e-01],
       [-4.43635777e-01],
       [-4.91455659e-01],
       [ 3.60679280e+00],
       [ 4.99255516e-01],
       [-3.78280596e-01],
       [ 4.89103607e-01],
       [-5.02948539e-01],
       [-1.13845709e-01],
       [-3.76603377e-01],
       [-4.86337422e-01],
       [-4.92714077e-01],
       [ 1.58417891e+00],
       [-4.94391297e-01],
       [ 3.93272305e+00],
       [-1.19131064e-01],
       [-3.57390858e-01],
       [-4.92544946e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-3.76603377e-01],
       [-1.19131064e-01],
       [ 2.40299019e+00],
       [-3.41452240e-01],
       [ 3.48329928e-01],
       [-1.13845709e-01],
       [ 3.98582080e-01],
       [-4.57478375e-01],
       [-3.86670720e-01],
       [-4.94391297e-01],
       [ 3.93272305e+00],
       [-4.37007438e-01],
       [-3.36334002e-01],
       [-4.91874461e-01],
       [ 1.60230236e-02],
       [-5.06387543e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [ 4.20730236e-01],
       [-4.74004926e-01],
       [-2.25593223e-01],
       [-4.92629511e-01],
       [-1.24919787e-01],
       [-4.88854258e-01],
       [ 3.60679280e+00],
       [-2.70141218e-01],
       [-6.48421654e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.24253190e-01],
       [ 4.37082185e-02],
       [ 9.66716653e+00],
       [-4.89442190e-01],
       [-4.89442190e-01],
       [-4.43810379e-02],
       [ 9.39198431e-01],
       [ 4.63441690e+00],
       [-3.24253190e-01],
       [-4.88854258e-01],
       [ 7.81141137e-01],
       [-2.40694238e-01],
       [-3.86670720e-01],
       [ 4.20730236e-01],
       [-4.92377828e-01],
       [-1.85323848e-01],
       [-3.97241431e-01],
       [-4.57142125e-01],
       [-4.89442190e-01],
       [ 6.60333014e-01],
       [-3.56468689e-01],
       [-4.91455659e-01],
       [-4.16872751e-01],
       [-4.86337422e-01],
       [ 1.09322879e+00],
       [-3.56468689e-01],
       [-5.04962007e-01],
       [-5.02863973e-01],
       [ 1.76774081e+00],
       [-4.91874461e-01],
       [ 9.21244331e-01],
       [ 1.48911959e-01],
       [-4.92377828e-01],
       [-1.62168958e-01],

In [23]:
df['Fare'] = fare_scaled

In [24]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age      Fare Embarked
0            1         0       3    male  22.0 -0.502445        S
1            2         1       1  female  38.0  0.786845        C
2            3         1       3  female  26.0 -0.488854        S
3            4         1       1  female  35.0  0.420730        S
4            5         0       3    male  35.0 -0.486337        S

In [25]:
scaler = preprocessing.MinMaxScaler()

In [26]:
fare_scaled = scaler.fit_transform(fare.reshape(-1, 1))

In [27]:
df['Fare'] = fare_scaled

In [28]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age      Fare Embarked
0            1         0       3    male  22.0  0.014151        S
1            2         1       1  female  38.0  0.139136        C
2            3         1       3  female  26.0  0.015469        S
3            4         1       1  female  35.0  0.103644        S
4            5         0       3    male  35.0  0.015713        S

In [35]:
one_hot_encoder = preprocessing.OneHotEncoder()

In [36]:
sex_one_hot_encoder = one_hot_encoder.fit_transform(df['Sex'].values.reshape(-1, 1))

In [37]:
one_hot_encoder.get_feature_names_out(['Sex'])

array(['Sex_female', 'Sex_male'], dtype=object)

In [38]:
sex_one_hot_encoder_values = sex_one_hot_encoder.toarray()

In [39]:
sex_one_hot_encoder_values.shape

(891, 2)

In [40]:
df[one_hot_encoder.get_feature_names_out(['Sex'])] = sex_one_hot_encoder_values

In [41]:
df

,PassengerId,Survived,Pclass,Sex,Age,Fare,Embarked,Sex_female,Sex_male
0,1,0,3,male,22.000000,0.014151,S,0.0,1.0
1,2,1,1,female,38.000000,0.139136,C,1.0,0.0
2,3,1,3,female,26.000000,0.015469,S,1.0,0.0
3,4,1,1,female,35.000000,0.103644,S,1.0,0.0
4,5,0,3,male,35.000000,0.015713,S,0.0,1.0
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0.025374,S,0.0,1.0
887,888,1,1,female,19.000000,0.058556,S,1.0,0.0
888,889,0,3,female,29.699118,0.045771,S,1.0,0.0
889,890,1,1,male,26.000000,0.058556,C,0.0,1.0
890,891,0,3,male,32.000000,0.015127,Q,0.0,1.0